### ISSUE TITLE
Paper wallet Segwit (bech32) address QR is upper case.

### ISSUE THREAD

**Issue by bom64** [Kimbatt/btc-address-generator#4]
All bech32 is when decoding the QR code in upper case.

**Comment by Kimbatt** [comment]
> For presentation, lowercase is usually preferable, but inside QR codes uppercase SHOULD be used, as those permit the use of alphanumeric mode, which is 45% more compact than the normal byte mode. 

from https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki#specification  
  
I also mentioned this on the information section of the site (second paragraph).
