### ISSUE TITLE
bip38 encryption on custom address

### ISSUE THREAD

**Issue by Eegee** [Kimbatt/btc-address-generator#5]
It would be nice to allow use of bip38 encryption on the custom/own address in the Paper wallet tab. Currently the encryption is applied only to the generated addresses.

**Comment by Kimbatt** [comment]
You can now encrypt custom private keys:
In the paper wallet tab, checking "Bip38 encrypt" will change the "Use your own addresses" checkbox to "Use your own private keys", where you can enter your private keys.
