### ISSUE TITLE
Enhancement proposal join functionality from page=paperwallet and page=seed to new page

### ISSUE THREAD

**Issue by tlindi** [Kimbatt/btc-address-generator#7]
As an HD Wallet user - I'd like to print paperwallets with bech32 from my recovery phrase (24 words) derived addresses.

I have found no such functionality on any paperwallet generator.

To me (not coder) it doesn't seem to be hard to implement - as current application has all the functions already - they only are not available on the same page. 
1) page=seed provides all needed functions to calculate addresses and
2) page=paperwallet has all needed functinality to print wallets with nice layouts

Unfortunately page=paperwallet has no ability to enter my own seed - so I cant print addresses from my seed.

I thnk it might be beneficial for many people to have something like page=paperwalletsfromseed ?

Where functions from above to pages would be merged / joined?

br, tlindi

**Comment by Kimbatt** [comment]
There is now an option on the paper wallet generation page to generate the addresses from a mnemonic seed.
